name: Nuclei Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Nuclei - Fast Vulnerability Scan
        uses: projectdiscovery/nuclei-action@v1
        with:
          urls: domains.txt
          flags: "-severity critical,high,medium -c 50 -rate-limit 100 -timeout 5"

      - name: Upload Nuclei Report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-scan-results
          path: nuclei-report.json
